image: python:3.13-bookworm

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends gcc make jq
  - python -m pip install -r requirements-test.txt

supported-pipeline:
  stage: test
  script:
    - ./tests/run_supported.sh
